-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 11:18:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- (Raquel) Añadido y conecta a la base de datos
ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weriumGames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weriumGames` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `weriumGames`;

-- -----------------------------------------------------
-- Table `weriumGames`.`tabla_angulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weriumGames`.`tabla_angulos` (
  `id_registro` DOUBLE NOT NULL AUTO_INCREMENT,
  `id_sesion` DOUBLE NULL DEFAULT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `alfa` DOUBLE NULL DEFAULT NULL,
  `beta` DOUBLE NULL DEFAULT NULL,
  `gamma` DOUBLE NULL DEFAULT NULL,
  `posX` DOUBLE NULL DEFAULT NULL,
  `posY` DOUBLE NULL DEFAULT NULL,
  `posZ` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_registro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weriumGames`.`tabla_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weriumGames`.`tabla_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `edad` INT NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weriumGames`.`tabla_sesiones`    (CONFIGURACIONES) 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weriumGames`.`tabla_sesiones` (     
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `numero_sesion` INT NULL DEFAULT NULL,
  `juego` INT NULL DEFAULT NULL,
  `numero_objetivos` INT NULL DEFAULT NULL,
  `articulacion` INT NULL DEFAULT NULL,
  `lado` INT NULL DEFAULT NULL,
  `eje`  INT NULL DEFAULT NULL,
  `horizontalmax` INT NULL DEFAULT NULL,
  `horizontalMin` INT NULL DEFAULT NULL,
  `verticalMax` INT NULL DEFAULT NULL,
  `verticalMin` INT NULL DEFAULT NULL,
  `velocidad` INT NULL DEFAULT NULL,
  `movimiento` INT NULL DEFAULT NULL,

  
  PRIMARY KEY (`id_sesion`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `weriumGames`.`tabla_angulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weriumGames`.`tabla_objetivos` (
  `id_objetivo` INT NOT NULL AUTO_INCREMENT,
  `id_sesion` INT NULL DEFAULT NULL,
  `n_objetivo` VARCHAR(45) NULL DEFAULT NULL,
  `angulo_x`  VARCHAR(45) NULL DEFAULT NULL,
  `angulo_y`  VARCHAR(45) NULL DEFAULT NULL,
  `posicion_x`  VARCHAR(45) NULL DEFAULT NULL,
  `posicion_y`  VARCHAR(45) NULL DEFAULT NULL,
  `posicion_z`  VARCHAR(45) NULL DEFAULT NULL,
  `tiempo`  VARCHAR(45) NULL DEFAULT NULL,
  `alcanzado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_objetivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
